### ISSUE TITLE
生成エラーなのかわからないが生成できない

### ISSUE THREAD

**Issue by mikage-961pro** [kanno2inf/VReducer#34]
以下のエラーで生成できない。
対処方法を教えて欲しい。

```
combine hair primitives...
shrink materials...
sort face primitives...
combine materials...
Traceback (most recent call last):
  File "vreducer.py", line 66, in <module>
    main(sys.argv[1:])
  File "vreducer.py", line 42, in main
    vrm.gltf = reduce_vroid(vrm.gltf, opt.replace_shade_color, parse_texture_size(opt.texture_size), opt.emissive_color)
  File "/Users/apple/Downloads/VReducer-0.3.0/vrm/reducer.py", line 650, in reduce_vroid
    }, 'F00_002_Onepi', texture_size)
  File "/Users/apple/Downloads/VReducer-0.3.0/vrm/reducer.py", line 451, in combine_material
    texture = vrm_material['textureProperties']['_MainTex']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by kanno2inf** [comment]
@mikage-961pro 
本リポジトリのバージョンがVRoidStudio最新版に対応していないのでエラーが出ていると思われます。
とりあえずこちらのforkリポジトリ版を試してもらえますか？→https://github.com/mainyaa/VReducer

**Comment by mikage-961pro** [comment]
以下のようなエラーだと思うんですがログが出ました。

```
Traceback (most recent call last):
  File "vreducer.py", line 9, in <module>
    from vrm.debug import print_stat
  File "/Users/apple/VReducer/vrm/debug.py", line 7
SyntaxError: Non-ASCII character '\xe3' in file /Users/apple/VReducer/vrm/debug.py on line 8, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
該当モデル：
https://mikage-stone.geo.jp/vrm-models/VRoid.vrm.zip

**Comment by kanno2inf** [comment]
@mikage-961pro 
masterに修正を入れましたので試してみてください。おそらく直ったはず。

**Comment by mikage-961pro** [comment]
まだエラーが出るようです。

```
  File "vreducer.py", line 14
SyntaxError: Non-ASCII character '\xe3' in file vreducer.py on line 14, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

そちらの環境で該当モデルが変換できているようであればそちらもいただけると幸いです。

**Comment by kanno2inf** [comment]
こちら変換後モデルです。
→ https://drive.google.com/file/d/12H4uortm5ODnXivUmvPifS-4pTea9cwl/view?usp=sharing

python2だとこのエラーが出るみたいなのでpython3.8以上で試してもらえますか？

**Comment by mikage-961pro** [comment]
```
Mac@MacPro: python vreducer.py VRoid.vrm -e            

  File "vreducer.py", line 14
SyntaxError: Non-ASCII character '\xe3' in file vreducer.py on line 14, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
って出てしまいますね。

あと変換後のこの辺をどうにかする機能ってありますでしょうか？
![スクリーンショット 2020-06-25 10 40 33](https://user-images.githubusercontent.com/50665049/85643914-77591100-b6d0-11ea-8cad-9f3b63337ff5.png)

**Comment by kanno2inf** [comment]
python3系で実行できてない可能性が高いので```$ python -V```でバージョン確認してもらえますか。

VReducer自体にはポリゴン数やボーン数の削減機能はないので、別途Blenderなどを使ってください。
